TIME_FORMAT = 'H:i'
TIME_INPUT_FORMATS = ('%H:%M','%H:%M:%S')

DATE_FORMAT = 'j. N Y'
SHORT_DATE_FORMAT = 'j. N'

MONTH_FORMAT = 'N Y'

DATETIME_FORMAT = 'j. N Y, H:i'
SHORT_DATETIME_FORMAT = 'j. N H:i'