#!/bin/bash
if [[ ${0} != "deploy/bootstrap_dev" ]]; then
    echo "only call this from within the source root of a template project"
    exit 1;
fi;

VIRTUAL_ENV="env"

mkdir media static coverage

virtualenv --distribute --no-site-packages $VIRTUAL_ENV || virtualenv --no-site-packages $VIRTUAL_ENV 

echo "export DJANGO_SETTINGS_MODULE=settings.dev" >> $VIRTUAL_ENV/bin/postactivate
echo "unset DJANGO_SETTINGS_MODULE" >> $VIRTUAL_ENV/bin/postdeactivate
source $VIRTUAL_ENV/bin/activate

add2virtualenv "$(pwd)/src"

for dir in env/lib/*/site-packages/; do
    if [[ ! -f $dir/projecttemplate.pth ]]; then
        echo "$(pwd)/src" > $dir/projecttemplate.pth
    fi
done;

pip install -r deploy/requirements.txt

if [[ ! -f src/projecttemplate/settings/local.py ]]; then
    echo "from devel import *" >> src/projecttemplate/settings/local.py
fi
