#!/bin/bash
if [[ ${0} != "deploy/bootstrap_dev" ]]; then
    echo "only call this from within the source root of a template project"
    exit 1;
fi;

VIRTUAL_ENV="env"

mkdir media static coverage

if [[ ! -d $VIRTUAL_ENV ]]; then
    virtualenv --distribute --no-site-packages $VIRTUAL_ENV || virtualenv --no-site-packages $VIRTUAL_ENV 

    echo "export DJANGO_SETTINGS_MODULE=youarehero.settings.local" >> $VIRTUAL_ENV/bin/activate
    source $VIRTUAL_ENV/bin/activate

# probably not relevant anymore with 1.4 layout
#    for dir in env/lib/*/site-packages/; do
#        if [[ ! -f $dir/youarehero.pth ]]; then
#            echo "$(pwd)/src" > $dir/youarehero.pth
#        fi
#    done;
fi;

if [[ ! -d .idea ]]; then
    cp -r deploy/dot_idea .idea;
fi;


pip install -r deploy/requirements.txt
easy_install readline

if [[ ! -f src/youarehero/settings/local.py ]]; then
    echo "from devel import *" >> src/youarehero/settings/local.py
fi
