#!/bin/bash
if [[ ${0} != "deploy/initialize_this" ]]; then
    echo "only call this from within the source root of a template project"
    exit 1;
fi;
project_name=$1

if [[ -z ${project_name} ]]; then
    echo "Usage: $0 project_name"
    exit 1
fi

if [[ ! -d src/projecttemplate ]]; then
    echo "This project has already been customized, aborting";
    exit 1
fi

sed -i '' -e 's/url = .*/url = DEFINE_GIT_URL_IN_GIT_CONFIG/' .git/config

for file in .gitignore src/manage.py src/projecttemplate/settings/base.py src/projecttemplate/urls.py src/projecttemplate/wsgi.py deploy/bootstrap_dev docs/index.rst docs/conf.py docs/Makefile docs/make.bat deploy/dot_idea/* deploy/dot_idea/.name; 
    do sed -i '' -e "s/projecttemplate/$project_name/g" $file;
done;

SECRET_KEY=$(python -c 'from random import choice; import sys; sys.stdout.write("".join([choice("abcdefghijklmnopqrstuvwxyz0123456789%^&*(-_=+)") for i in range(50)]))')
echo "SECRET_KEY = '$SECRET_KEY'" >> src/projecttemplate/settings/base.py


git mv src/projecttemplate src/$project_name
git mv deploy/dot_idea/projecttemplate.iml deploy/dot_idea/$project_name.iml
git rm deploy/initialize_this

git commit -a -m "initialized project as $project_name"
echo "Initialized project $project_name"
