# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'QuestProfile'
        db.create_table('herorecommend_questprofile', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('example0', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example1', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example2', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example3', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example4', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example5', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example6', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example7', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example8', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example9', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example10', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example11', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example12', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example13', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example14', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example15', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example16', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example17', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example18', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example19', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example20', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example21', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example22', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example23', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example24', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example25', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example26', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example27', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example28', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example29', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example30', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example31', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example32', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example33', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example34', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example35', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example36', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example37', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example38', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example39', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example40', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example41', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example42', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example43', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example44', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example45', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example46', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example47', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example48', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example49', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('quest', self.gf('django.db.models.fields.related.OneToOneField')(related_name='profile', unique=True, to=orm['herobase.Quest'])),
            ('average', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('root_sum_of_squares', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example0', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example1', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example2', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example3', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example4', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example5', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example6', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example7', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example8', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example9', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example10', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example11', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example12', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example13', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example14', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example15', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example16', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example17', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example18', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example19', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example20', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example21', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example22', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example23', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example24', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example25', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example26', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example27', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example28', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example29', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example30', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example31', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example32', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example33', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example34', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example35', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example36', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example37', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example38', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example39', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example40', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example41', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example42', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example43', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example44', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example45', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example46', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example47', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example48', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('delta_example49', self.gf('django.db.models.fields.FloatField')(default=0)),
        ))
        db.send_create_signal('herorecommend', ['QuestProfile'])

        # Adding model 'UserSelectionProfile'
        db.create_table('herorecommend_userselectionprofile', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('example0', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example1', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example2', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example3', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example4', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example5', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example6', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example7', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example8', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example9', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example10', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example11', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example12', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example13', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example14', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example15', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example16', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example17', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example18', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example19', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example20', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example21', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example22', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example23', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example24', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example25', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example26', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example27', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example28', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example29', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example30', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example31', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example32', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example33', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example34', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example35', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example36', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example37', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example38', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example39', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example40', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example41', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example42', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example43', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example44', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example45', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example46', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example47', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example48', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example49', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('user', self.gf('django.db.models.fields.related.OneToOneField')(related_name='selection_profile', unique=True, to=orm['auth.User'])),
        ))
        db.send_create_signal('herorecommend', ['UserSelectionProfile'])

        # Adding model 'UserRatingProfile'
        db.create_table('herorecommend_userratingprofile', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('example0', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example1', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example2', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example3', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example4', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example5', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example6', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example7', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example8', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example9', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example10', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example11', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example12', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example13', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example14', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example15', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example16', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example17', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example18', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example19', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example20', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example21', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example22', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example23', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example24', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example25', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example26', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example27', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example28', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example29', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example30', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example31', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example32', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example33', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example34', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example35', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example36', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example37', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example38', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example39', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example40', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example41', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example42', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example43', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example44', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example45', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example46', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example47', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example48', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example49', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('user', self.gf('django.db.models.fields.related.OneToOneField')(related_name='rating_profile', unique=True, to=orm['auth.User'])),
        ))
        db.send_create_signal('herorecommend', ['UserRatingProfile'])

        # Adding model 'UserCombinedProfile'
        db.create_table('herorecommend_usercombinedprofile', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('example0', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example1', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example2', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example3', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example4', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example5', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example6', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example7', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example8', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example9', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example10', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example11', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example12', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example13', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example14', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example15', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example16', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example17', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example18', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example19', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example20', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example21', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example22', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example23', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example24', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example25', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example26', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example27', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example28', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example29', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example30', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example31', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example32', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example33', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example34', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example35', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example36', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example37', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example38', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example39', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example40', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example41', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example42', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example43', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example44', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example45', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example46', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example47', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example48', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('example49', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('user', self.gf('django.db.models.fields.related.OneToOneField')(related_name='combined_profile', unique=True, to=orm['auth.User'])),
        ))
        db.send_create_signal('herorecommend', ['UserCombinedProfile'])

        # Adding model 'QuestRating'
        db.create_table('herorecommend_questrating', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user', self.gf('django.db.models.fields.related.ForeignKey')(related_name='ratings', to=orm['auth.User'])),
            ('quest', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['herobase.Quest'])),
            ('like', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('apply', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('participate', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('participate_plus', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
        ))
        db.send_create_signal('herorecommend', ['QuestRating'])


    def backwards(self, orm):
        # Deleting model 'QuestProfile'
        db.delete_table('herorecommend_questprofile')

        # Deleting model 'UserSelectionProfile'
        db.delete_table('herorecommend_userselectionprofile')

        # Deleting model 'UserRatingProfile'
        db.delete_table('herorecommend_userratingprofile')

        # Deleting model 'UserCombinedProfile'
        db.delete_table('herorecommend_usercombinedprofile')

        # Deleting model 'QuestRating'
        db.delete_table('herorecommend_questrating')


    models = {
        'auth.group': {
            'Meta': {'object_name': 'Group'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        'auth.permission': {
            'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')", 'unique_together': "(('content_type', 'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'unique': 'True', 'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'herobase.adventure': {
            'Meta': {'object_name': 'Adventure'},
            'created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'quest': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['herobase.Quest']"}),
            'state': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'adventures'", 'to': "orm['auth.User']"})
        },
        'herobase.quest': {
            'Meta': {'object_name': 'Quest'},
            'auto_accept': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.TextField', [], {}),
            'due_date': ('django.db.models.fields.DateTimeField', [], {}),
            'experience': ('django.db.models.fields.PositiveIntegerField', [], {}),
            'hero_class': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'heroes': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'quests'", 'symmetrical': 'False', 'through': "orm['herobase.Adventure']", 'to': "orm['auth.User']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'level': ('django.db.models.fields.PositiveIntegerField', [], {}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'max_heroes': ('django.db.models.fields.PositiveIntegerField', [], {'default': '1'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'owner': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'created_quests'", 'to': "orm['auth.User']"}),
            'state': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        'herorecommend.questprofile': {
            'Meta': {'object_name': 'QuestProfile'},
            'average': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example0': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example1': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example10': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example11': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example12': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example13': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example14': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example15': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example16': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example17': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example18': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example19': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example2': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example20': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example21': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example22': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example23': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example24': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example25': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example26': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example27': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example28': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example29': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example3': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example30': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example31': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example32': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example33': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example34': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example35': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example36': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example37': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example38': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example39': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example4': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example40': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example41': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example42': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example43': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example44': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example45': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example46': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example47': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example48': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example49': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example5': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example6': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example7': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example8': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'delta_example9': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example0': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example1': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example10': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example11': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example12': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example13': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example14': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example15': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example16': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example17': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example18': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example19': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example2': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example20': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example21': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example22': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example23': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example24': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example25': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example26': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example27': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example28': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example29': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example3': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example30': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example31': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example32': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example33': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example34': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example35': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example36': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example37': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example38': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example39': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example4': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example40': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example41': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example42': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example43': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example44': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example45': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example46': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example47': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example48': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example49': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example5': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example6': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example7': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example8': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example9': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'quest': ('django.db.models.fields.related.OneToOneField', [], {'related_name': "'profile'", 'unique': 'True', 'to': "orm['herobase.Quest']"}),
            'root_sum_of_squares': ('django.db.models.fields.FloatField', [], {'default': '0'})
        },
        'herorecommend.questrating': {
            'Meta': {'object_name': 'QuestRating'},
            'apply': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'like': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'participate': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'participate_plus': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'quest': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['herobase.Quest']"}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ratings'", 'to': "orm['auth.User']"})
        },
        'herorecommend.usercombinedprofile': {
            'Meta': {'object_name': 'UserCombinedProfile'},
            'example0': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example1': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example10': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example11': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example12': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example13': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example14': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example15': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example16': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example17': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example18': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example19': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example2': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example20': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example21': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example22': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example23': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example24': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example25': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example26': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example27': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example28': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example29': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example3': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example30': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example31': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example32': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example33': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example34': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example35': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example36': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example37': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example38': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example39': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example4': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example40': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example41': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example42': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example43': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example44': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example45': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example46': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example47': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example48': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example49': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example5': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example6': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example7': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example8': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example9': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'related_name': "'combined_profile'", 'unique': 'True', 'to': "orm['auth.User']"})
        },
        'herorecommend.userratingprofile': {
            'Meta': {'object_name': 'UserRatingProfile'},
            'example0': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example1': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example10': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example11': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example12': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example13': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example14': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example15': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example16': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example17': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example18': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example19': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example2': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example20': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example21': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example22': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example23': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example24': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example25': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example26': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example27': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example28': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example29': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example3': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example30': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example31': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example32': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example33': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example34': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example35': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example36': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example37': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example38': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example39': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example4': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example40': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example41': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example42': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example43': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example44': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example45': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example46': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example47': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example48': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example49': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example5': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example6': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example7': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example8': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example9': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'related_name': "'rating_profile'", 'unique': 'True', 'to': "orm['auth.User']"})
        },
        'herorecommend.userselectionprofile': {
            'Meta': {'object_name': 'UserSelectionProfile'},
            'example0': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example1': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example10': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example11': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example12': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example13': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example14': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example15': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example16': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example17': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example18': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example19': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example2': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example20': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example21': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example22': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example23': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example24': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example25': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example26': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example27': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example28': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example29': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example3': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example30': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example31': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example32': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example33': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example34': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example35': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example36': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example37': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example38': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example39': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example4': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example40': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example41': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example42': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example43': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example44': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example45': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example46': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example47': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example48': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example49': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example5': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example6': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example7': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example8': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'example9': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'related_name': "'selection_profile'", 'unique': 'True', 'to': "orm['auth.User']"})
        }
    }

    complete_apps = ['herorecommend']